USE GymManagementDB;
GO

DELETE FROM dbo.BOOKING
WHERE MemberID = 11 AND SessionID = 7;
GO

SELECT * FROM dbo.BOOKING
WHERE MemberID = 11 AND SessionID = 7;
GO

DELETE FROM dbo.MEMBER
WHERE MemberID = 11;
GO

SELECT * FROM dbo.MEMBER
WHERE MemberID = 11;
GO